# Default Project Configuration

title="Configuration"

[data]
doc_path = 'data/raw/EDGAR/2016'
gensim_dictionary_path = 'data/interim/bowdict.gensim'
file_limit = 100
req_str = '10-K-A'
save_path = 'data/processed/'
[data.split]
train = 0.8
valid = 0.1
test = 0.1

[logging]
version = 1
disable_existing_loggers = true
[logging.formatters.verbose]
format = '%(levelname)s %(name)s: %(message)s'
[logging.formatters.simple]
format = '%(levelname)s: %(message)s'
[logging.handlers.default]
level = 'INFO'
formatter = 'simple'
class = 'logging.StreamHandler'
stream = 'ext://sys.stdout'
[logging.root]
handlers = ['default']
level = 'WARNING'
[logging.loggers.fintopics]
handlers = ['default']
level = 'INFO'
propogate = false
